FROM alpine:3.15

RUN set -ex && echo "https://mirrors.aliyun.com/alpine/v3.15/community" > /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/v3.15/main" >> /etc/apk/repositories \
    && apk update \
    && apk add --no-cache --update bash nodejs npm \
    && node -v && npm -v 

WORKDIR /app/squoosh/

# the source code is at https://github.com/GoogleChromeLabs/squoosh, I just edited the package.json file, set port 
COPY squoosh /app/squoosh/

RUN cd /app/squoosh && npm install && npm i -g @squoosh/cli

EXPOSE 8080

ENTRYPOINT ["npm","run","serve"]